# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: skempiData.yaml
  - model: AffinityPrediction.yaml
  - callbacks: default.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# inference (i.e., sampling) and evaluation arguments
seed: 42
  
# passing checkpoint path is necessary for sampling and evaluation
ckpt_path: "/path/to/PackPPI_affinity_fold0/1/2.ckpt"
